name: Push-to-EC2

# Trigger deployment only on push to staging branch
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Deploy to EC2 on master branch push
    runs-on: self-hosted

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: restart pm2
        run: pm2 restart all
